### ISSUE TITLE
Error on initializing popup

### ISSUE THREAD

**Issue by kimaniidaniel** [vast-engineering/jquery-popup-overlay#101]
When I call the .popup function to initialize the popup i get the below error. Any reason why?
jQuery.Deferred exception: Object doesn't support property or method 'popup' TypeError: Object doesn't support property or method 'popup'
   at Anonymous function (https://go2fete.com/boxoffice/:12:9)
   at e (https://code.jquery.com/jquery-3.4.1.min.js:2:29445)
   at Anonymous function (https://code.jquery.com/jquery-3.4.1.min.js:2:29755) undefined

**Comment by kimaniidaniel** [comment]
Fixed! I just needed to position the script tag in the right place in the html file
